/**
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CorrelationPropertyArray } from '../model/correlationPropertyArray';
import { DataElementInstanceArrayWithLinks } from '../model/dataElementInstanceArrayWithLinks';
import { DataElementInstanceWithLinks } from '../model/dataElementInstanceWithLinks';
import { InvalidInput } from '../model/invalidInput';
import { NotFound } from '../model/notFound';

import { TRADE_BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DataElementInstanceService {

    protected basePath = 'https://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(TRADE_BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Gets all available &#x60;DataElementInstance&#x60; resources. Optional query parameter of **start** and **size** enable pagination of the collection of data element instance resources and param **status** filters result list by status of the data element instances.
     * @param start Start index of returned collection of resources for pagination.
     * @param size Size of the returned sub-collection of resources for pagination.
     * @param status Status of data element instances to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllDataElementInstances(start?: number, size?: number, status?: string, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceArrayWithLinks>;
    public getAllDataElementInstances(start?: number, size?: number, status?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceArrayWithLinks>>;
    public getAllDataElementInstances(start?: number, size?: number, status?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceArrayWithLinks>>;
    public getAllDataElementInstances(start?: number, size?: number, status?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (status !== undefined) {
            queryParameters = queryParameters.set('status', <any>status);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DataElementInstanceArrayWithLinks>(`${this.basePath}/dataElementInstances`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find a data element instance by Id
     * 
     * @param instanceId Id of the data element instance that needs to be fetched
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDataElementInstance(instanceId: string, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceWithLinks>;
    public getDataElementInstance(instanceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceWithLinks>>;
    public getDataElementInstance(instanceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceWithLinks>>;
    public getDataElementInstance(instanceId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (instanceId === null || instanceId === undefined) {
            throw new Error('Required parameter instanceId was null or undefined when calling getDataElementInstance.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DataElementInstanceWithLinks>(`${this.basePath}/dataElementInstances/${encodeURIComponent(String(instanceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a data element instance from a data object instance by the name of the corresponding data element
     * 
     * @param instanceId Id of the data object instance that needs to be fetched
     * @param dataElementName The name of the data element for which we want to get the instance from the current data object instance
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDataElementInstanceByDataElementName(instanceId: string, dataElementName: string, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceWithLinks>;
    public getDataElementInstanceByDataElementName(instanceId: string, dataElementName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceWithLinks>>;
    public getDataElementInstanceByDataElementName(instanceId: string, dataElementName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceWithLinks>>;
    public getDataElementInstanceByDataElementName(instanceId: string, dataElementName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (instanceId === null || instanceId === undefined) {
            throw new Error('Required parameter instanceId was null or undefined when calling getDataElementInstanceByDataElementName.');
        }
        if (dataElementName === null || dataElementName === undefined) {
            throw new Error('Required parameter dataElementName was null or undefined when calling getDataElementInstanceByDataElementName.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DataElementInstanceWithLinks>(`${this.basePath}/dataObjectInstances/${encodeURIComponent(String(instanceId))}/elementInstances/${encodeURIComponent(String(dataElementName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Gets all available &#x60;DataElementInstance&#x60; resources. Optional query parameter of **start** and **size** enable pagination of the collection of data element instance resources and param **status** filters result list by status of the data element instances.
     * @param instanceId Id of the data object instance that needs to be fetched
     * @param start Start index of returned collection of resources for pagination.
     * @param size Size of the returned sub-collection of resources for pagination.
     * @param status Status of data element instances to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDataElementInstances(instanceId: string, start?: number, size?: number, status?: string, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceArrayWithLinks>;
    public getDataElementInstances(instanceId: string, start?: number, size?: number, status?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceArrayWithLinks>>;
    public getDataElementInstances(instanceId: string, start?: number, size?: number, status?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceArrayWithLinks>>;
    public getDataElementInstances(instanceId: string, start?: number, size?: number, status?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (instanceId === null || instanceId === undefined) {
            throw new Error('Required parameter instanceId was null or undefined when calling getDataElementInstances.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (status !== undefined) {
            queryParameters = queryParameters.set('status', <any>status);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DataElementInstanceArrayWithLinks>(`${this.basePath}/dataObjectInstances/${encodeURIComponent(String(instanceId))}/elementInstances`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Gets all available &#x60;DataElementInstance&#x60; resources. Optional query parameter of **start** and **size** enable pagination of the collection of data element instance resources and param **status** filters result list by status of the data element instances.
     * @param dataElementId Id of the data element that needs to be fetched
     * @param start Start index of returned collection of resources for pagination.
     * @param size Size of the returned sub-collection of resources for pagination.
     * @param status Status of data element instances to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDataElementInstancesOfDataElement(dataElementId: string, start?: number, size?: number, status?: string, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceArrayWithLinks>;
    public getDataElementInstancesOfDataElement(dataElementId: string, start?: number, size?: number, status?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceArrayWithLinks>>;
    public getDataElementInstancesOfDataElement(dataElementId: string, start?: number, size?: number, status?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceArrayWithLinks>>;
    public getDataElementInstancesOfDataElement(dataElementId: string, start?: number, size?: number, status?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (dataElementId === null || dataElementId === undefined) {
            throw new Error('Required parameter dataElementId was null or undefined when calling getDataElementInstancesOfDataElement.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (status !== undefined) {
            queryParameters = queryParameters.set('status', <any>status);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DataElementInstanceArrayWithLinks>(`${this.basePath}/dataElements/${encodeURIComponent(String(dataElementId))}/instances`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Provides a list of all data element instances that use/refer to the data value with the given id. Optional query parameter of **start** and **size** enable pagination of the collection of data element instance resources.
     * 
     * @param dataValueId Id of the data value that needs to be fetched
     * @param start Start index of returned collection of resources for pagination.
     * @param size Size of the returned sub-collection of resources for pagination.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDataElementInstancesUsingDataValue(dataValueId: string, start?: number, size?: number, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceArrayWithLinks>;
    public getDataElementInstancesUsingDataValue(dataValueId: string, start?: number, size?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceArrayWithLinks>>;
    public getDataElementInstancesUsingDataValue(dataValueId: string, start?: number, size?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceArrayWithLinks>>;
    public getDataElementInstancesUsingDataValue(dataValueId: string, start?: number, size?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (dataValueId === null || dataValueId === undefined) {
            throw new Error('Required parameter dataValueId was null or undefined when calling getDataElementInstancesUsingDataValue.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DataElementInstanceArrayWithLinks>(`${this.basePath}/dataValues/${encodeURIComponent(String(dataValueId))}/elementInstances`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Query an available &#x60;DataElementInstance&#x60; resource based on specified parameters. Query parameters **dataModelName**, **dataObjectName** and **dataElementName** as well as **correlationProperties** transfered as request body are used as a query to find a matching data element instance.
     * @param dataModelNamespace Namespace of the data model a data object instance should belong to.
     * @param dataModelName Name of the data model a data element instance should belong to.
     * @param dataObjectName The name of the data object the instance should belong to.
     * @param dataElementName The name of the data element the instance should belong to.
     * @param correlationProperties An array of correlation properties associated with the searched data element instance.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public queryDataElementInstance(dataModelNamespace: string, dataModelName: string, dataObjectName: string, dataElementName: string, correlationProperties: CorrelationPropertyArray, observe?: 'body', reportProgress?: boolean): Observable<DataElementInstanceWithLinks>;
    public queryDataElementInstance(dataModelNamespace: string, dataModelName: string, dataObjectName: string, dataElementName: string, correlationProperties: CorrelationPropertyArray, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DataElementInstanceWithLinks>>;
    public queryDataElementInstance(dataModelNamespace: string, dataModelName: string, dataObjectName: string, dataElementName: string, correlationProperties: CorrelationPropertyArray, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DataElementInstanceWithLinks>>;
    public queryDataElementInstance(dataModelNamespace: string, dataModelName: string, dataObjectName: string, dataElementName: string, correlationProperties: CorrelationPropertyArray, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (dataModelNamespace === null || dataModelNamespace === undefined) {
            throw new Error('Required parameter dataModelNamespace was null or undefined when calling queryDataElementInstance.');
        }
        if (dataModelName === null || dataModelName === undefined) {
            throw new Error('Required parameter dataModelName was null or undefined when calling queryDataElementInstance.');
        }
        if (dataObjectName === null || dataObjectName === undefined) {
            throw new Error('Required parameter dataObjectName was null or undefined when calling queryDataElementInstance.');
        }
        if (dataElementName === null || dataElementName === undefined) {
            throw new Error('Required parameter dataElementName was null or undefined when calling queryDataElementInstance.');
        }
        if (correlationProperties === null || correlationProperties === undefined) {
            throw new Error('Required parameter correlationProperties was null or undefined when calling queryDataElementInstance.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dataModelNamespace !== undefined) {
            queryParameters = queryParameters.set('dataModelNamespace', <any>dataModelNamespace);
        }
        if (dataModelName !== undefined) {
            queryParameters = queryParameters.set('dataModelName', <any>dataModelName);
        }
        if (dataObjectName !== undefined) {
            queryParameters = queryParameters.set('dataObjectName', <any>dataObjectName);
        }
        if (dataElementName !== undefined) {
            queryParameters = queryParameters.set('dataElementName', <any>dataElementName);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<DataElementInstanceWithLinks>(`${this.basePath}/dataElementInstances`,
            correlationProperties,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
