/**
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { NotFound } from '../model/notFound';
import { NotifierService } from '../model/notifierService';
import { NotifierServiceArrayWithLinks } from '../model/notifierServiceArrayWithLinks';

import { TRADE_BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class NotifierServiceService {

    protected basePath = 'https://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(TRADE_BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Find a notifier service by Id
     * 
     * @param notifierServiceId Id of the notifier service that needs to be fetched
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNotifierServiceDirectly(notifierServiceId: string, observe?: 'body', reportProgress?: boolean): Observable<NotifierService>;
    public getNotifierServiceDirectly(notifierServiceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NotifierService>>;
    public getNotifierServiceDirectly(notifierServiceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NotifierService>>;
    public getNotifierServiceDirectly(notifierServiceId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (notifierServiceId === null || notifierServiceId === undefined) {
            throw new Error('Required parameter notifierServiceId was null or undefined when calling getNotifierServiceDirectly.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NotifierService>(`${this.basePath}/notifierServices/${encodeURIComponent(String(notifierServiceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the associated notifier service of this notification
     * 
     * @param notificationId Id of the notification for which the notifier service should to be fetched
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNotifierServiceOfNotification(notificationId: string, observe?: 'body', reportProgress?: boolean): Observable<NotifierService>;
    public getNotifierServiceOfNotification(notificationId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NotifierService>>;
    public getNotifierServiceOfNotification(notificationId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NotifierService>>;
    public getNotifierServiceOfNotification(notificationId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (notificationId === null || notificationId === undefined) {
            throw new Error('Required parameter notificationId was null or undefined when calling getNotifierServiceOfNotification.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NotifierService>(`${this.basePath}/notifications/${encodeURIComponent(String(notificationId))}/notifierService`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Gets all available &#x60;NotifierService&#x60; resources. Optional query parameter of **start** and **size** enable pagination of the collection of notifier service resources.
     * @param start Start index of returned collection of resources for pagination.
     * @param size Size of the returned sub-collection of resources for pagination.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNotifierServices(start?: number, size?: number, observe?: 'body', reportProgress?: boolean): Observable<NotifierServiceArrayWithLinks>;
    public getNotifierServices(start?: number, size?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NotifierServiceArrayWithLinks>>;
    public getNotifierServices(start?: number, size?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NotifierServiceArrayWithLinks>>;
    public getNotifierServices(start?: number, size?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NotifierServiceArrayWithLinks>(`${this.basePath}/notifierServices`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
