/**
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataObjectArray } from './dataObjectArray';
import { LinkArray } from './linkArray';


export interface DataObjectArrayWithLinks {
    dataObjects?: DataObjectArray;
    links?: LinkArray;
}
