/**
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Notification {
    id?: string;

    href?: string;

    name?: string;

    typeOfResourceToObserve?: models.ResourceTypeEnum;

    idOfResourceToObserve?: string;

    resourceFilters?: models.ResourceEventFilterArray;

    selectedNotifierServiceId?: string;

    notifierParameterValues?: models.NotifierServiceParameterArray;

}
