/**
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ResourceTypeEnum = 'DataDependencyGraph' | 'DataModel' | 'DataObject' | 'DataElement' | 'DataObjectInstance' | 'DataElementInstance' | 'DataValue';

export const ResourceTypeEnum = {
    DataDependencyGraph: 'DataDependencyGraph' as ResourceTypeEnum,
    DataModel: 'DataModel' as ResourceTypeEnum,
    DataObject: 'DataObject' as ResourceTypeEnum,
    DataElement: 'DataElement' as ResourceTypeEnum,
    DataObjectInstance: 'DataObjectInstance' as ResourceTypeEnum,
    DataElementInstance: 'DataElementInstance' as ResourceTypeEnum,
    DataValue: 'DataValue' as ResourceTypeEnum
}
