/**
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LinkArray } from './linkArray';
import { ResourceEventFilterDescriptionArray } from './resourceEventFilterDescriptionArray';


export interface ResourceEventFilterDescriptionArrayWithLinks {
    resourceFilterDescriptions?: ResourceEventFilterDescriptionArray;
    links?: LinkArray;
}
