/**
 * HDTApps Framework
 * Handling data transformation applications (HDTApps) framework's API specification 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationAppInfo } from './applicationAppInfo';
import { ApplicationDependencies } from './applicationDependencies';
import { Configuration } from './configuration';
import { InvocationCLI } from './invocationCLI';
import { TestRun } from './testRun';
import { Transformation } from './transformation';


export interface Application {
    appInfo?: ApplicationAppInfo;
    transformations?: Array<Transformation>;
    dependencies?: ApplicationDependencies;
    configurations?: Array<Configuration>;
    invocations?: Array<InvocationCLI>;
    testRuns?: Array<TestRun>;
}
