/**
 * HDTApps Framework
 * Handling data transformation applications (HDTApps) framework's API specification 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InputFileSet {
    name?: string;
    alias?: string;
    isOptional?: boolean;
    format?: string;
    schemaPath?: string;
    requiredPath?: string;
    fileSetSize?: string;
    fileName?: string;
}
