/**
 * HDTApps Framework
 * Handling data transformation applications (HDTApps) framework's API specification 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Provider } from './provider';
import { RequestInputFile } from './requestInputFile';
import { RequestInputFileSet } from './requestInputFileSet';
import { RequestInputParameter } from './requestInputParameter';


export interface TransformationRequest {
    appID?: string;
    transformationID?: string;
    resultsEndpoint?: string;
    providers?: Array<Provider>;
    inputParams?: Array<RequestInputParameter>;
    inputFiles?: Array<RequestInputFile>;
    inputFileSets?: Array<RequestInputFileSet>;
}
