/**
 * HDTApps Framework
 * Handling data transformation applications (HDTApps) framework's API specification 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InputFile } from './inputFile';
import { InputFileSet } from './inputFileSet';
import { InputParameter } from './inputParameter';
import { OutputFile } from './outputFile';
import { Provider } from './provider';


export interface Transformation {
    name?: string;
    qname?: string;
    appID?: string;
    transformationID?: string;
    providers?: Array<Provider>;
    /**
     * including optional input parameters
     */
    strictSignature?: string;
    /**
     * excluding optional input parameters
     */
    relaxedSignature?: string;
    /**
     * including optional input parameters and using MIME types
     */
    strictMIMESignature?: string;
    /**
     * excluding optional input parameters  and using MIME types
     */
    relaxedMIMESignature?: string;
    inputTotalParamCount?: number;
    inputNumericParamCount?: number;
    inputStringParamCount?: number;
    inputParams?: Array<InputParameter>;
    inputFileCount?: number;
    inputFiles?: Array<InputFile>;
    inputFileSetCount?: number;
    inputFileSets?: Array<InputFileSet>;
    outputFileCount?: number;
    outputFiles?: Array<OutputFile>;
}
